
# extensions
load('ext://secret', 'secret_create_generic', 'secret_from_dict', 'secret_yaml_registry')

# deploy local infro
config = '''
deployers:
  - type: argocd
    name: my-beta-cluster
    endpoint: argocd-server.argocd.svc.cluster.local
    authtoken: {argocdToken}
vcs:
  type: github
  authtoken: {githubToken}
'''.format(
  argocdToken=os.environ['ARGOCD_TOKEN'],
  githubToken=os.environ['GITHUB_TOKEN'],
)
k8s_yaml(secret_from_dict("infro-secrets", "infro", inputs={
    'config': config,
    'owner': 'infro-io',
}))
k8s_yaml('../../deploy/install.yaml')

# deploy local argocd
k8s_yaml(kustomize('./argocd'))

# expose argocd api server
k8s_resource(workload='argocd-server', port_forwards=8080)

# wait for argocd CRDs
k8s_resource(
  objects=['example-helm:application'],
  resource_deps=['argocd-server'],
  new_name='example-helm-application',
)
